// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    def versions = [:]

    versions.android_gradle_plugin = '8.5.0'

    versions.kotlin = '1.9.24'

    versions.kotlin_coroutines = '1.8.0'

    versions.jetbrains_annotations = '24.0.1'

    versions.android_multidex = '2.0.1'

    versions.android_appcompat = '1.7.0'

    versions.android_documentfile = '1.0.1'
    versions.android_localbroadcastmanager = '1.1.0'

    versions.android_cardview = '1.0.0'
    versions.android_recyclerview = '1.3.2'
    versions.android_viewpager = '1.0.0'
    versions.android_constraint_layout = '2.1.4'
    versions.android_preference = '1.2.1'
    versions.android_material = '1.12.0'
    versions.android_swiperefreshlayout = '1.1.0'

    versions.android_room = '2.6.1'

    versions.android_lifecycle = '2.8.2'

    versions.android_annotation = '1.7.0'

    versions.android_workmanager = '2.9.0'

    versions.junit = '4.13.2'

    versions.android_test_espresso = '3.5.1'

    versions.android_test_runner = '1.5.2'

    versions.android_test_rules = '1.5.0'

    versions.android_test_ext_junit = '1.1.5'

    versions.android_test_uiautomator = '2.3.0'

    versions.org_java = '1.3-SNAPSHOT'

    versions.loremipsum = '1.0'

    versions.dagger = '2.51.1'

    versions.gson = '2.10.1'

    versions.dropbox_core_sdk = '5.4.6'

    versions.juniversalchardet = '1.0.3'

    versions.joda_time = '2.12.5'

    versions.glide = '4.14.2'

    versions.sardine = '0.8'

    versions.okhttp_digest = '3.1.0'

    versions.jgit = '5.13.0.202109080827-r'

    ext.versions = versions

    repositories {
        mavenCentral()
        google()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:$versions.android_gradle_plugin"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$versions.kotlin"
    }
}

allprojects {
    repositories {
        mavenCentral()

        google()

        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }

        // For sardine-android
        maven {
            url 'https://jitpack.io'
        }
    }

    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}
